#!/usr/bin/env bash

workdir=$(cd `dirname ${0}`; pwd)

docker run --rm -p 80:80 -p 443:443 \
    -v ${workdir}/letsencrypt:/etc/letsencrypt \
    quay.io/letsencrypt/letsencrypt:latest auth \
    --standalone -m jibo@onlymaker.com --agree-tos \
    -d onlymaker.com -d www.onlymaker.com
