#!/usr/bin/env bash

nginx=`docker ps|grep nginx|awk '{print $NF}'`

docker stop $nginx

workdir=$(cd `dirname ${0}`; pwd)

if [ "$1"x == createx ]; then
    echo create
    docker run --rm -p 80:80 -p 443:443 \
        -v ${workdir}/letsencrypt:/etc/letsencrypt \
        certbot/certbot:v0.19.0 certonly \
        --standalone -m jibo@onlymaker.com --agree-tos \
        -d onlymaker.com
elif [ "$1"x == renewx ] || [ "$1"x == x ]; then
    echo renew
    docker run --rm -p 80:80 -p 443:443 \
        -v ${workdir}/letsencrypt:/etc/letsencrypt \
        certbot/certbot:v0.19.0 renew \
        --standalone --force-renewal
else
    echo Unknown options $1
fi

docker start $nginx
