#!/usr/bin/env bash
workdir=$(cd `dirname ${0}`; pwd)
docker exec -it `basename ${workdir}`_oce_1 chown -R www-data:www-data /var/www/html
docker exec -it `basename ${workdir}`_opencart_1 chown -R www-data:www-data /var/www/html
docker exec -it `basename ${workdir}`_pure-ftpd_1 chmod -R ug+w /home/ftpusers/
docker exec -it `basename ${workdir}`_pure-ftpd_1 usermod -a -G www-data ftpuser
